version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

commands:
  environment_setup:
    description: setup an environment with only pip
    steps:
    - run: sudo pip install twine wheel pytest pytest-cov pytest-mock
  create_pypi_file:
    description: create .pypi file in ~/
    steps:
      - run:
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "  pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username: gsy0911" >> ~/.pypirc
            echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc
      - run: cat ~/.pypirc
  create_deployment_package_and_deploy:
    description: create deployment package and deploy to pypi
    steps:
      - run:
          command: |
            python setup.py sdist bdist_wheel
            twine upload -r pypi dist/*

jobs:
  python_test_3_6:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - environment_setup
      - run: pytest ./test -vv --cov=./slack_api_decorator --cov-report=xml
  python_test_3_7:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - environment_setup
      - run: pytest ./test -vv --cov=./slack_api_decorator --cov-report=xml
  python_test_3_8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - environment_setup
      - run: pytest ./test -vv --cov=./slack_api_decorator --cov-report=xml
      - codecov/upload:
        file: ./test/coverage.xml
  deploy_to_pypi:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - environment_setup
      - create_pypi_file
      - create_deployment_package_and_deploy


workflows:
  version: 2
  process:
    jobs:
      - python_test_3_6:
          filters:
            branches:
              only:
                - master
      - python_test_3_7:
          filters:
            branches:
              only:
                - master
      - python_test_3_8
      - deploy_to_pypi:
          requires:
            - python_test_3_6
            - python_test_3_7
            - python_test_3_8
          filters:
            branches:
              only:
                - master